jrc_vecinos:
    resource: "@JRCVecinosBundle/Resources/config/routing.yml"
    prefix:   /

jrc_user:
    resource: "@JRCUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
