jrc_usuario_usuario:
    resource: "@JRCVecinosBundle/Resources/config/routes/usuario.yml"
    prefix:   /usuario

jrc_task_task:
    resource: "@JRCVecinosBundle/Resources/config/routes/comunidad.yml"
    prefix:   /comunidad


jrc_vecinos_homepage:
    path:     /vecinos/{name}
    defaults: { _controller: JRCVecinosBundle:Vecinos:index }


