jrc_comunidad_index:
    path:   /index
    defaults: { _controller: JRCVecinosBundle:Comunidad:index }
    
jrc_comunidad_add:
    path:    /add
    defaults: { _controller: JRCVecinosBundle:Comunidad:add }
    
jrc_comunidad_create:
    path:   /create
    defaults: { _controller: JRCVecinosBundle:Comunidad:create }
    methods: POST
    
jrc_comunidad_edit:
    path:   /edit/{id}
    defaults: { _controller: JRCVecinosBundle:Comunidad:edit }
    
jrc_comunidad_update:
    path:       /update/{id}
    defaults: { _controller: JRCVecinosBundle:Comunidad:update }
    methods: [POST, PUT]
    
jrc_comunidad_view:
    path:       /view/{id}
    defaults: { _controller: JRCVecinosBundle:Comunidad:view }
    
jrc_comunidad_delete:
    path:       /delete{id}
    defaults: { _controller: JRCVecinosBundle:Comunidad:delete }
    methods: [POST, DELETE]
    
jrc_comunidad_redirect_add:
    path:   /create
    defaults:
        _controller: JRCVecinosBundle:Comunidad:add
        path: /comunidad/add
        permanent: true