<?php

namespace JRC\VecinosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComunidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComunidadRepository extends EntityRepository
{
}
